/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2023-03-21 02:03:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("jar:file:/D:/ProjectWs/PettoSupplies/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-bean.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("jar:file:/D:/ProjectWs/PettoSupplies/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098687690000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-taglib-1.3.8.jar", Long.valueOf(1679363862393L));
    _jspx_dependants.put("jar:file:/D:/ProjectWs/PettoSupplies/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-html.tld", Long.valueOf(1172892492000L));
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1679363862344L));
    _jspx_dependants.put("/WEB-INF/jsp/inc/common.jsp", Long.valueOf(1679363861760L));
    _jspx_dependants.put("jar:file:/D:/ProjectWs/PettoSupplies/WEB-INF/lib/struts-taglib-1.3.8.jar!/META-INF/tld/struts-logic.tld", Long.valueOf(1172892492000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.release();
    _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.release();
    _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_logic_005fredirect_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/shared.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css1/home-style.css\" type=\"text/css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div class=\"position-fixed w-100 nav-div top-0\">\r\n");
      out.write("\t\t<nav\r\n");
      out.write("\t\t\tclass=\"navbar navbar-expand-lg navbar-light border-bottom border-1 border-dark\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"#\"> <img\r\n");
      out.write("\t\t\t\tsrc=\"images/paw-print-clip-art-heart.png\" alt=\"\" width=\"50\"\r\n");
      out.write("\t\t\t\tclass=\"rounded-circle\"> </a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\"\r\n");
      out.write("\t\t\t\tdata-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("\t\t\t\taria-controls=\"navbarSupportedContent\" aria-expanded=\"false\"\r\n");
      out.write("\t\t\t\taria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link active\"\r\n");
      out.write("\t\t\t\t\t\taria-current=\"page\" href=\"#\">Pet Needs</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\tShop By Pet </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t");
      //  logic:notEmpty
      org.apache.struts.taglib.logic.NotEmptyTag _jspx_th_logic_005fnotEmpty_005f0 = (org.apache.struts.taglib.logic.NotEmptyTag) _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.get(org.apache.struts.taglib.logic.NotEmptyTag.class);
      _jspx_th_logic_005fnotEmpty_005f0.setPageContext(_jspx_page_context);
      _jspx_th_logic_005fnotEmpty_005f0.setParent(null);
      // /WEB-INF/jsp/index.jsp(61,7) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f0.setProperty("petsList");
      // /WEB-INF/jsp/index.jsp(61,7) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_logic_005fnotEmpty_005f0.setName("HomeFormBean");
      int _jspx_eval_logic_005fnotEmpty_005f0 = _jspx_th_logic_005fnotEmpty_005f0.doStartTag();
      if (_jspx_eval_logic_005fnotEmpty_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t");
          //  logic:iterate
          org.apache.struts.taglib.logic.IterateTag _jspx_th_logic_005fiterate_005f0 = (org.apache.struts.taglib.logic.IterateTag) _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.get(org.apache.struts.taglib.logic.IterateTag.class);
          _jspx_th_logic_005fiterate_005f0.setPageContext(_jspx_page_context);
          _jspx_th_logic_005fiterate_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_logic_005fnotEmpty_005f0);
          // /WEB-INF/jsp/index.jsp(62,8) name = id type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_logic_005fiterate_005f0.setId("pet");
          // /WEB-INF/jsp/index.jsp(62,8) name = property type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_logic_005fiterate_005f0.setProperty("petsList");
          // /WEB-INF/jsp/index.jsp(62,8) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_logic_005fiterate_005f0.setName("HomeFormBean");
          int _jspx_eval_logic_005fiterate_005f0 = _jspx_th_logic_005fiterate_005f0.doStartTag();
          if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            java.lang.Object pet = null;
            if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.pushBody();
              _jspx_th_logic_005fiterate_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
              _jspx_th_logic_005fiterate_005f0.doInitBody();
            }
            pet = (java.lang.Object) _jspx_page_context.findAttribute("pet");
            do {
              out.write("\r\n");
              out.write("\t\t\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"petPagePath.do?frmPetId=");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write('"');
              out.write('>');
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pet.petName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
              out.write("</a></li>\r\n");
              out.write("\t\t\t\t\t\t\t\t");
              int evalDoAfterBody = _jspx_th_logic_005fiterate_005f0.doAfterBody();
              pet = (java.lang.Object) _jspx_page_context.findAttribute("pet");
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
            if (_jspx_eval_logic_005fiterate_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
              out = _jspx_page_context.popBody();
            }
          }
          if (_jspx_th_logic_005fiterate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
            return;
          }
          _005fjspx_005ftagPool_005flogic_005fiterate_0026_005fproperty_005fname_005fid.reuse(_jspx_th_logic_005fiterate_005f0);
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_logic_005fnotEmpty_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_logic_005fnotEmpty_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
        return;
      }
      _005fjspx_005ftagPool_005flogic_005fnotEmpty_0026_005fproperty_005fname.reuse(_jspx_th_logic_005fnotEmpty_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item dropdown\"><a\r\n");
      out.write("\t\t\t\t\t\tclass=\"nav-link dropdown-toggle\" href=\"#\" id=\"navbarDropdown\"\r\n");
      out.write("\t\t\t\t\t\trole=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t\t\tShop By Category </a>\r\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"shop_category.html\">Dog\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFoods</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Dog Beds and\r\n");
      out.write("\t\t\t\t\t\t\t\t\tFuniture</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Cat Foods</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t\t<li><a class=\"dropdown-item\" href=\"#\">Fish Foods</a>\r\n");
      out.write("\t\t\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t\t</ul></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t<a href=\"login.html\" class=\"nav-link text-decoration-none\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-user-circle fa-2x m-0\"></i>\r\n");
      out.write("\t\t\t\t</a> <a href=\"cart.html\" class=\"nav-link text-decoration-none\"><i\r\n");
      out.write("\t\t\t\t\tclass=\"fa fa-shopping-cart fa-2x m-0\"></i>\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t<form class=\"d-flex\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control me-2\" type=\"search\" placeholder=\"Search\"\r\n");
      out.write("\t\t\t\t\t\taria-label=\"Search\">\r\n");
      out.write("\t\t\t\t\t<button class=\"btn btn-outline-danger\" type=\"submit\">Search</button>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</nav>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"section-home border-bottom border-1 border-dark\">\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t\t<div class=\"row home\">\r\n");
      out.write("\t\t\t<div class=\"home-text-box col-md-5 col-12\">\r\n");
      out.write("\t\t\t\t<h1 class=\"heading-primary  mt-3\">Pet accessories to your\r\n");
      out.write("\t\t\t\t\tlovely pets.</h1>\r\n");
      out.write("\t\t\t\t<p class=\"home-description\">Lorem ipsum dolor sit amet\r\n");
      out.write("\t\t\t\t\tconsectetur adipisicing elit. Eligendi nobis odio similique labore\r\n");
      out.write("\t\t\t\t\tdeleniti in reprehenderit amet a totam. Assumenda a aspernatur quae\r\n");
      out.write("\t\t\t\t\tvelit rerum accusamus voluptatibus culpa rem quod.</p>\r\n");
      out.write("\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red btn-big\">Learn more\r\n");
      out.write("\t\t\t\t\t&darr;</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"home-img-box col-md-7 col-12\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Doggie.png\" class=\"home-img\"\r\n");
      out.write("\t\t\t\t\talt=\"A dog and a girl.\">\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"border-bottom border-1 border-dark\">\r\n");
      out.write("\t<div class=\"all-pet-container\">\r\n");
      out.write("\t\t<h2 class=\"heading-secondary text-center\">Shop by Pet</h2>\r\n");
      out.write("\t\t<div class=\"container-fluid py-2 overflow-scroll overflow-hidden\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"d-flex flex-row flex-nowrap justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"pet-card col-sm-3 col-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pet-img-container\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/Happy-Dog334.jpg\" class=\"pet-img\" alt=\"Dog\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Dog<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"link\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"pet-card col-sm-3 col-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pet-img-container\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/Pretty-Cat334.jpg\" class=\"pet-img\" alt=\"Dog\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Cat<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"pet-card-link\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"pet-card col-sm-3 col-6 text-center\">\r\n");
      out.write("\t\t\t\t\t<div class=\"pet-img-container\">\r\n");
      out.write("\t\t\t\t\t\t<img src=\"images/Red-Fish334.jpg\" class=\"pet-img\" alt=\"Dog\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Fish<span\r\n");
      out.write("\t\t\t\t\t\tclass=\"link\"></span>\r\n");
      out.write("\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"border-bottom border-1 border-dark\">\r\n");
      out.write("\t<h2 class=\"heading-secondary text-center\">Latest Products</h2>\r\n");
      out.write("\t<div class=\"container-fluid py-2 overflow-scroll mt-5\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"d-flex flex-row flex-nowrap justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"product-card col-lg-2 col-6 mb-3\">\r\n");
      out.write("\t\t\t\t<img src=\"images/blue_buffalo_front.jpg\" class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\talt=\"...\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h6 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\tBlue Buffalo Life Protection Formula Natural Adult Dry Dog Food,\r\n");
      out.write("\t\t\t\t\t\tChicken and Brown Rice 30-lb\r\n");
      out.write("\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">5400 ks</p>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"align-content-center\">\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Detail<span\r\n");
      out.write("\t\t\t\t\t\t\t\tclass=\"link\"></span>\r\n");
      out.write("\t\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"product-card col-lg-2 col-6 mb-3\">\r\n");
      out.write("\t\t\t\t<img src=\"images/cesar_front.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h6 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\tCESAR Soft Wet Dog Food Classic Loaf in Sauce Beef Recipe\r\n");
      out.write("\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">3000 ks</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Detail<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"link\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"product-card col-lg-2 col-6 mb-3\">\r\n");
      out.write("\t\t\t\t<img src=\"images/Iamso_front.jpg\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h6 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\tIAMS PROACTIVE HEALTH Adult Minichunks Small Kibble High Protein\r\n");
      out.write("\t\t\t\t\t\tDry Dog Food with Real Chicken, 30 lb. Bag\r\n");
      out.write("\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">3500 ks</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Detail<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"link\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"product-card col-lg-2 col-6 mb-3\">\r\n");
      out.write("\t\t\t\t<img src=\"images/kibble_bits_front.jpg\" class=\"card-img-top\"\r\n");
      out.write("\t\t\t\t\talt=\"...\">\r\n");
      out.write("\t\t\t\t<div class=\"card-body\">\r\n");
      out.write("\t\t\t\t\t<h6 class=\"card-title\">\r\n");
      out.write("\t\t\t\t\t\tKibbles 'N Bits Original Savory Beef & Chicken Flavors Dry Dog\r\n");
      out.write("\t\t\t\t\t\tFood\r\n");
      out.write("\t\t\t\t\t\t</h5>\r\n");
      out.write("\t\t\t\t\t\t<p class=\"card-text\">3300 ks</p>\r\n");
      out.write("\t\t\t\t\t\t<a href=\"#\" type=\"button\" class=\"btn btn-red\">Detail<span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"link\"></span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<!-- <div class=\"product-card col-lg-2 col-6 mb-3\">\r\n");
      out.write("                    <img src=\"images/Doggie500x375.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5 class=\"card-title\">Some quick example text to build on the card title.</h5>\r\n");
      out.write("                      <p class=\"card-text\">40000 ks</p>\r\n");
      out.write("                      <a href=\"#\" class=\"btn text-white\" style=\"background-color: #f6615a;\">Detail<span class=\"link\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"product-card col-lg-2 col-6 mb-3\">\r\n");
      out.write("                    <img src=\"images/Doggie500x375.png\" class=\"card-img-top\" alt=\"...\">\r\n");
      out.write("                    <div class=\"card-body\">\r\n");
      out.write("                      <h5 class=\"card-title\">Make up the bulk of the card's content.</h5>\r\n");
      out.write("                      <p class=\"card-text\">30200 ks</p>\r\n");
      out.write("                      <a href=\"#\" class=\"btn text-white\" style=\"background-color: #f6615a;\">Detail<span class=\"link\"></span></a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div> -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section class=\"border-bottom border-1 border-dark\">\r\n");
      out.write("\r\n");
      out.write("\t<h2 class=\"heading-secondary text-center\">Shop by Category</h2>\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row justify-content-between\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"category-card col-sm-5 col-6\">\r\n");
      out.write("\t\t\t\t<h5 class=\"category-card-title\">Dog</h5>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"category-card-text d-block\">Dog Foods</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"#\" class=\"category-card-text d-block\">Dog Beds & Funiture</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"category-card-text d-block\">Dog Health and\r\n");
      out.write("\t\t\t\t\tWellness</a> <a href=\"#\" class=\"category-card-text d-block\">Dog\r\n");
      out.write("\t\t\t\t\tClothing and Shoess</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"category-card col-sm-4 col-6\">\r\n");
      out.write("\t\t\t\t<h5 class=\"category-card-title\">Cat</h5>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"category-card-text d-block\">Dog Foods</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"#\" class=\"category-card-text d-block\">Dog Beds & Funiture</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"category-card-text d-block\">Dog Health and\r\n");
      out.write("\t\t\t\t\tWellness</a> <a href=\"#\" class=\"category-card-text d-block\">Dog\r\n");
      out.write("\t\t\t\t\tClothing and Shoess</a> <a href=\"#\" class=\"category-card-text d-block\">Dog\r\n");
      out.write("\t\t\t\t\tFoods</a> <a href=\"#\" class=\"category-card-text d-block\">Dog Beds &\r\n");
      out.write("\t\t\t\t\tFuniture</a> <a href=\"#\" class=\"category-card-text d-block\">Dog\r\n");
      out.write("\t\t\t\t\tHealth and Wellness</a> <a href=\"#\" class=\"category-card-text d-block\">Dog\r\n");
      out.write("\t\t\t\t\tClothing and Shoess</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"category-card col-sm-3 col-6\">\r\n");
      out.write("\t\t\t\t<h5 class=\"category-card-title\">Fish</h5>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"category-card-text d-block\">Dog Foods</a> <a\r\n");
      out.write("\t\t\t\t\thref=\"#\" class=\"category-card-text d-block\">Dog Beds & Funiture</a>\r\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"category-card-text d-block\">Dog Health and\r\n");
      out.write("\t\t\t\t\tWellness</a> <a href=\"#\" class=\"category-card-text d-block\">Dog\r\n");
      out.write("\t\t\t\t\tClothing and Shoess</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_logic_005fredirect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  logic:redirect
    org.apache.struts.taglib.logic.RedirectTag _jspx_th_logic_005fredirect_005f0 = (org.apache.struts.taglib.logic.RedirectTag) _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.get(org.apache.struts.taglib.logic.RedirectTag.class);
    _jspx_th_logic_005fredirect_005f0.setPageContext(_jspx_page_context);
    _jspx_th_logic_005fredirect_005f0.setParent(null);
    // /WEB-INF/jsp/index.jsp(18,0) name = href type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_logic_005fredirect_005f0.setHref("homePath.do");
    int _jspx_eval_logic_005fredirect_005f0 = _jspx_th_logic_005fredirect_005f0.doStartTag();
    if (_jspx_th_logic_005fredirect_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.reuse(_jspx_th_logic_005fredirect_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005flogic_005fredirect_0026_005fhref_005fnobody.reuse(_jspx_th_logic_005fredirect_005f0);
    return false;
  }
}
